#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#    Jun 16, 2022 02:08:59 PM +0300  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import Metashape_interface_2_support

class Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = 'gray40' # X11 color: #666666
        _ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
        _ana2color = 'beige' # X11 color: #f5f5dc
        _tabfg1 = 'black' 
        _tabfg2 = 'black' 
        _tabbg1 = 'grey75' 
        _tabbg2 = 'grey89' 
        _bgmode = 'light' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x800+527+115")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(0,  0)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top
        self.che49 = tk.IntVar()

        self.style.map('TNotebook.Tab', background =
            [('selected', _bgcolor), ('active', _tabbg1),
            ('!active', _tabbg2)], foreground =
            [('selected', _fgcolor), ('active', _tabfg1), ('!active',  _tabfg2)])
        self.notebook_parameters = ttk.Notebook(self.top)
        self.notebook_parameters.place(x=10, y=20, height=726, width=574)
        self.notebook_parameters.configure(takefocus="")
        self.tab_match_align = tk.Frame(self.notebook_parameters)
        self.notebook_parameters.add(self.tab_match_align, padding=3)
        self.notebook_parameters.tab(0, text='''Match & Align''', compound="left"
                ,underline='''-1''', )
        self.tab_match_align.configure(background="#d9d9d9")
        self.tab_match_align.configure(highlightbackground="#d9d9d9")
        self.tab_match_align.configure(highlightcolor="black")
        self.tab_filtering = tk.Frame(self.notebook_parameters)
        self.notebook_parameters.add(self.tab_filtering, padding=3)
        self.notebook_parameters.tab(1, text='''Filtering''', compound="left"
                ,underline='''-1''', )
        self.tab_filtering.configure(background="#d9d9d9")
        self.tab_filtering.configure(highlightbackground="#d9d9d9")
        self.tab_filtering.configure(highlightcolor="black")
        self.tab_dense_cloud = tk.Frame(self.notebook_parameters)
        self.notebook_parameters.add(self.tab_dense_cloud, padding=3)
        self.notebook_parameters.tab(2, text='''Dense Cloud''', compound="left"
                ,underline='''-1''', )
        self.tab_dense_cloud.configure(background="#d9d9d9")
        self.tab_dense_cloud.configure(highlightbackground="#d9d9d9")
        self.tab_dense_cloud.configure(highlightcolor="black")
        self.tab_model = tk.Frame(self.notebook_parameters)
        self.notebook_parameters.add(self.tab_model, padding=3)
        self.notebook_parameters.tab(3, text='''Model''', compound="left"
                ,underline='''-1''', )
        self.tab_model.configure(background="#d9d9d9")
        self.tab_model.configure(highlightbackground="#d9d9d9")
        self.tab_model.configure(highlightcolor="black")
        self.tab_normal_maps = tk.Frame(self.notebook_parameters)
        self.notebook_parameters.add(self.tab_normal_maps, padding=3)
        self.notebook_parameters.tab(4, text='''Normal Maps''', compound="left"
                ,underline='''-1''', )
        self.tab_normal_maps.configure(background="#d9d9d9")
        self.tab_normal_maps.configure(highlightbackground="#d9d9d9")
        self.tab_normal_maps.configure(highlightcolor="black")
        self.tab_depth_maps = tk.Frame(self.notebook_parameters)
        self.notebook_parameters.add(self.tab_depth_maps, padding=3)
        self.notebook_parameters.tab(5, text='''Depth Maps''', compound="left"
                ,underline='''-1''', )
        self.tab_depth_maps.configure(background="#d9d9d9")
        self.tab_depth_maps.configure(highlightbackground="#d9d9d9")
        self.tab_depth_maps.configure(highlightcolor="black")
        self.tab_report = tk.Frame(self.notebook_parameters)
        self.notebook_parameters.add(self.tab_report, padding=3)
        self.notebook_parameters.tab(6, text='''Report''', compound="left"
                ,underline='''-1''', )
        self.tab_report.configure(background="#d9d9d9")
        self.tab_report.configure(highlightbackground="#d9d9d9")
        self.tab_report.configure(highlightcolor="black")

        self.frame_match = tk.LabelFrame(self.tab_match_align)
        self.frame_match.place(x=10, y=10, height=165, width=550)
        self.frame_match.configure(relief='groove')
        self.frame_match.configure(foreground="#000000")
        self.frame_match.configure(text='''Matching''')
        self.frame_match.configure(background="#d9d9d9")
        self.frame_match.configure(highlightbackground="#d9d9d9")
        self.frame_match.configure(highlightcolor="black")

        self.check_generic_preselection = tk.Checkbutton(self.frame_match)
        self.check_generic_preselection.place(x=20, y=90, height=25, width=135
                , bordermode='ignore')
        self.check_generic_preselection.configure(activebackground="beige")
        self.check_generic_preselection.configure(activeforeground="#000000")
        self.check_generic_preselection.configure(anchor='w')
        self.check_generic_preselection.configure(background="#d9d9d9")
        self.check_generic_preselection.configure(compound='left')
        self.check_generic_preselection.configure(disabledforeground="#a3a3a3")
        self.check_generic_preselection.configure(foreground="#000000")
        self.check_generic_preselection.configure(highlightbackground="#d9d9d9")
        self.check_generic_preselection.configure(highlightcolor="black")
        self.check_generic_preselection.configure(justify='left')
        self.check_generic_preselection.configure(selectcolor="#d9d9d9")
        self.check_generic_preselection.configure(text='''Generic Preselection''')
        self.check_generic_preselection.configure(variable=self.che49)

        self.entry_keypoint_limit = ttk.Entry(self.frame_match)
        self.entry_keypoint_limit.place(x=20, y=30, height=21, width=126
                , bordermode='ignore')
        self.entry_keypoint_limit.configure(takefocus="")
        self.entry_keypoint_limit.configure(cursor="ibeam")

        self.entry_tiepoint_limit = ttk.Entry(self.frame_match)
        self.entry_tiepoint_limit.place(x=20, y=60, height=21, width=126
                , bordermode='ignore')
        self.entry_tiepoint_limit.configure(takefocus="")
        self.entry_tiepoint_limit.configure(cursor="ibeam")

        self.check_reference_preselection = tk.Checkbutton(self.frame_match)
        self.check_reference_preselection.place(x=20, y=120, height=25, width=151
                , bordermode='ignore')
        self.check_reference_preselection.configure(activebackground="beige")
        self.check_reference_preselection.configure(activeforeground="#000000")
        self.check_reference_preselection.configure(anchor='w')
        self.check_reference_preselection.configure(background="#d9d9d9")
        self.check_reference_preselection.configure(compound='left')
        self.check_reference_preselection.configure(disabledforeground="#a3a3a3")
        self.check_reference_preselection.configure(foreground="#000000")
        self.check_reference_preselection.configure(highlightbackground="#d9d9d9")
        self.check_reference_preselection.configure(highlightcolor="black")
        self.check_reference_preselection.configure(justify='left')
        self.check_reference_preselection.configure(selectcolor="#d9d9d9")
        self.check_reference_preselection.configure(text='''Reference Preselection''')
        self.check_reference_preselection.configure(variable=self.che49)

        self.label_keypoint_limit = tk.Label(self.frame_match)
        self.label_keypoint_limit.place(x=150, y=30, height=21, width=83
                , bordermode='ignore')
        self.label_keypoint_limit.configure(activebackground="#f9f9f9")
        self.label_keypoint_limit.configure(anchor='w')
        self.label_keypoint_limit.configure(background="#d9d9d9")
        self.label_keypoint_limit.configure(compound='left')
        self.label_keypoint_limit.configure(disabledforeground="#a3a3a3")
        self.label_keypoint_limit.configure(foreground="#000000")
        self.label_keypoint_limit.configure(highlightbackground="#d9d9d9")
        self.label_keypoint_limit.configure(highlightcolor="black")
        self.label_keypoint_limit.configure(text='''Keypoint Limit''')

        self.label_tiepoint_limit = tk.Label(self.frame_match)
        self.label_tiepoint_limit.place(x=150, y=60, height=21, width=83
                , bordermode='ignore')
        self.label_tiepoint_limit.configure(activebackground="#f9f9f9")
        self.label_tiepoint_limit.configure(anchor='w')
        self.label_tiepoint_limit.configure(background="#d9d9d9")
        self.label_tiepoint_limit.configure(compound='left')
        self.label_tiepoint_limit.configure(disabledforeground="#a3a3a3")
        self.label_tiepoint_limit.configure(foreground="#000000")
        self.label_tiepoint_limit.configure(highlightbackground="#d9d9d9")
        self.label_tiepoint_limit.configure(highlightcolor="black")
        self.label_tiepoint_limit.configure(text='''Tiepoint Limit''')

        self.frame_align = tk.LabelFrame(self.tab_match_align)
        self.frame_align.place(x=700, y=120, height=505, width=550)
        self.frame_align.configure(relief='groove')
        self.frame_align.configure(foreground="#000000")
        self.frame_align.configure(text='''Alignment''')
        self.frame_align.configure(background="#d9d9d9")
        self.frame_align.configure(highlightbackground="#d9d9d9")
        self.frame_align.configure(highlightcolor="black")

        self.entry_tiepoint_limit = ttk.Entry(self.frame_align)
        self.entry_tiepoint_limit.place(x=20, y=60, height=21, width=126
                , bordermode='ignore')
        self.entry_tiepoint_limit.configure(takefocus="")
        self.entry_tiepoint_limit.configure(cursor="ibeam")

        self.entry_min_image = ttk.Entry(self.frame_align)
        self.entry_min_image.place(x=20, y=30, height=21, width=126
                , bordermode='ignore')
        self.entry_min_image.configure(takefocus="")
        self.entry_min_image.configure(cursor="ibeam")

        self.entry_tiepoint_limit_2 = ttk.Entry(self.frame_align)
        self.entry_tiepoint_limit_2.place(x=20, y=90, height=21, width=126
                , bordermode='ignore')
        self.entry_tiepoint_limit_2.configure(takefocus="")
        self.entry_tiepoint_limit_2.configure(cursor="ibeam")

        self.entry_tiepoint_limit_2_1 = ttk.Entry(self.frame_align)
        self.entry_tiepoint_limit_2_1.place(x=20, y=120, height=21, width=126
                , bordermode='ignore')
        self.entry_tiepoint_limit_2_1.configure(takefocus="")
        self.entry_tiepoint_limit_2_1.configure(cursor="ibeam")

        self.label_min_image = tk.Label(self.frame_align)
        self.label_min_image.place(x=150, y=30, height=21, width=154
                , bordermode='ignore')
        self.label_min_image.configure(activebackground="#f9f9f9")
        self.label_min_image.configure(anchor='w')
        self.label_min_image.configure(background="#d9d9d9")
        self.label_min_image.configure(compound='left')
        self.label_min_image.configure(disabledforeground="#a3a3a3")
        self.label_min_image.configure(foreground="#000000")
        self.label_min_image.configure(highlightbackground="#d9d9d9")
        self.label_min_image.configure(highlightcolor="black")
        self.label_min_image.configure(text='''Min Image''')

        self.button_process = tk.Button(self.top)
        self.button_process.place(x=210, y=760, height=24, width=177)
        self.button_process.configure(activebackground="beige")
        self.button_process.configure(activeforeground="#000000")
        self.button_process.configure(background="#d9d9d9")
        self.button_process.configure(command=Metashape_interface_2_support.process)
        self.button_process.configure(compound='left')
        self.button_process.configure(disabledforeground="#a3a3a3")
        self.button_process.configure(foreground="#000000")
        self.button_process.configure(highlightbackground="#d9d9d9")
        self.button_process.configure(highlightcolor="black")
        self.button_process.configure(pady="0")
        self.button_process.configure(text='''Process''')

def start_up():
    Metashape_interface_2_support.main()

if __name__ == '__main__':
    Metashape_interface_2_support.main()




